### ISSUE TITLE
`attempt to subtract with overflow` error when parsing id3 crc32

### ISSUE THREAD

**Issue by aschey** [pdeljanov/Symphonia#102]
Running [this file](https://mega.nz/file/szRABbDb#1HvTGjQ-IrNGTlCPuSNkQ5BgFctejtW2LEWg02iUtWQ) with symphonia-play results in the following error: `thread 'main' panicked at 'attempt to subtract with overflow', symphonia-metadata/src/id3v2/unsync.rs:21:58`. The error comes from [this line](https://github.com/pdeljanov/Symphonia/blob/87eef4916ef976ea335e3051ac62a1187d1782f7/symphonia-metadata/src/id3v2/unsync.rs#L21) and particularly this bit: `(bit_width - bits_read)`. Most places call this function with a bit width of 28, which works okay because `bits_read` is incremented by 7 each time which divides evenly into 28. However, when this is called with a bit width of 32 on [this line](https://github.com/pdeljanov/Symphonia/blob/87eef4916ef976ea335e3051ac62a1187d1782f7/symphonia-metadata/src/id3v2/mod.rs#L215), it causes the while loop [here](https://github.com/pdeljanov/Symphonia/blob/87eef4916ef976ea335e3051ac62a1187d1782f7/symphonia-metadata/src/id3v2/unsync.rs#L19) to perform the following calculations for `(bit_width - bits_read)`:
```rust
32 - 7
32 - 14
32 - 21
32 - 28
32 - 35
```
Once it gets to the last line it overflows since it goes negative. I was able to fix this by changing the while loop to the following:
```rust
while bits_read < bit_width {
    // Ensure bits_read never exceeds the bit width which will cause an overflow
    bits_read = (bits_read + 7).min(bit_width);
    result |= u32::from(reader.read_u8()? & 0x7f) << (bit_width - bits_read);
}
```
After making this change, symphonia-play prints out all the tags as expected. If this is the correct approach, I'd be happy to make a PR for this. Just wanted to check if this is the correct way to fix it first. Thanks!

**Comment by pdeljanov** [comment]
Hi @aschey,

Thank you for the thoughtful bug report. I think your solution is correct. According to the [ID3v2.4](https://id3.org/id3v2.4.0-structure) spec. section 6.2:

> Synchsafe integers are integers that keep its highest bit (bit 7) zeroed, making seven bits out of eight available. Thus a 32 bit synchsafe integer can store 28 bits of information.

This function is supposed to hide that complexity. Since the CRC is 32-bits wide, this function should consume 5 bytes and combine the lower 7 bits from the first 4 bytes, and the lower 4 bits from the 5th byte to generate the final 32-bit integer.

I'd be very happy to have a PR to fix this. I would include it in the upcoming 0.5 release (Monday-ish). Could you also add a couple tests?

Thanks!

**Comment by aschey** [comment]
Thanks for the background info @pdeljanov, that makes sense to me. I'll get a PR together with some tests later today.
