### ISSUE TITLE
Decoding into samples

### ISSUE THREAD

**Issue by dataO1** [pdeljanov/Symphonia#108]
This is rather a question than a bug/enhancement request, i hope thats ok. Also, just as a heads up, i have absolutely zero knowledge in audio file formats and how they are encoded/decoded etc., which is probably, why this question comes up:

Why do the readers decode files in packages and not sample by sample? My guess is, that it either has to do something with performance or maybe because the `FormatReader` has to implement several Readers for different formats and some formats (for streaming especially) only handle packages? 
Also, is this symphonia specific or do most audio decoding libraries handle things like that?

The reason why i'm asking is: I've build a small audio player using symphonia and libpulse, and noticed that when toggling playback of an MP3 off and then back on, the last package is played twice, or at least there is some noticeable repetition in the played audio. My only explanation for this is, that it has to do something with the fact, that whole packages are send to the audio output stream. Maybe my implementation is also buggy, but i mainly used your reference implementation and made it handle some async key presses, the core code is the same.

**Comment by pdeljanov** [comment]
Hi @dataO1,

Some background would be required to explain this.

Audio encoders take a stream of audio samples and produce a stream of compressed bytes. This stream is known as the codec bitstream. However, an encoder cannot compress a continuous stream of samples. The samples must  chunked into groups that range in size from 100s to 1000s of samples. The codec will then compress this chunk and output a buffer of bytes. This buffer is known as a packet. This chunking is required for the compression algorithms to work.

These packets are then generally wrapped with some extra information (such as timing) and written out into a container format. Container formats allow multiple tracks (and thus codec bitstreams) to be stored in the same file. It also enables things such as seeking and adding metadata.

In Symphonia, a `FormatReader` reads a container and outputs `Packet`s. The packets are then consumed by a `Decoder` that outputs the chunks of audio.

So basically, the reason why Symphonia outputs audio in large chunks is because that's how it's encoded. An iterator over samples could be implemented, but fundamentally the audio samples must be decoded in chunks first.

---

To get to your problem. It sounds like you're pausing playback by opening and closing the audio output. The issue here is that you don't know how many samples the audio output played and thus when you create a new output to resume playback some samples may be replayed.

This is a difficult problem because you need to know how many samples the output played so you can skip them the next time you open the output. A sample iterator won't solve your problem here because all audio APIs take in chunks of samples not individual samples. Therefore, you will always run into this problem.

There are two decent option:

1. Only stop playback once the current chunk has been played. Then you can resume playback with a new chunk.
2. Some audio APIs provide a method to "pause" the output. On PulseAudio, this is accomplished with the cork function, but other APIs should have similar.

Either option will work, but the first may create a noticeable amount of latency since the chunks provided by the decoder may be large. You could potentially solve this by splitting up the chunks into smaller chunks. That way there is less time between chunks.

One other thing to note is that the audio output code in `symphonia-play` is nothing special. It's really just mean't to get things playing for testing. An audio output for an interactive player will be much more complex.

I hope this helps!

**Comment by dataO1** [comment]
Thank you so much for that detailed explanation!

> To get to your problem. It sounds like you're pausing playback by opening and closing the audio output. The issue here is that you don't know how many samples the audio output played and thus when you create a new output to resume playback some samples may be replayed.

That might be the case, i will try to pause after packages and reuse the audio output and see, if the delay is not too big. I guess the package size depends on the codec?
If im not happy with the potential delay, I will try the "cork" option you suggested.

Again, thank you so much, that really helped alot!

**Comment by pdeljanov** [comment]
Glad it helped!

Yes, the number of decoded samples per packet depends on the codec and is quite variable. For example, MP3 outputs chunks of length 576 or 1152, but FLAC can vary between 16 to 65535 samples. In the latter case, this could be over 1 second of audio at a typical sample rate.

**Comment by daniellga** [comment]
Hi @pdeljanov! Is there an easy way to control the output length? Let's suppose I want the packet to always output 1000 samples, when supported by that specific codec. Does symphonia provide an API for that? Thank you!

**Comment by pdeljanov** [comment]
Hey @daniellga, unfortunately no. The number of samples per packet is fixed by the codec, or sometimes, the container. Typically it's not too large.

Symphonia is a low-level library in this regard. There are higher level libraries like `rodio` or `kira` that use Symphonia as a decoder backend and provide more ergonomic interfaces.

If you want to build something yourself though, the `Decoder::last_decoded` function is pretty useful to access the last successfully decoded audio buffer. You can copy samples from that into your own buffer until your own buffer is full, or you need to read the next packet and continue the process.
