### ISSUE TITLE
m4a format ?

### ISSUE THREAD

**Issue by happysalada** [pdeljanov/Symphonia#115]
Hi, is parsing the m4a format implemented ?
If I try adding the "isomp4" format, it says the codec is unsupported.
If I don't add the feature, reading the file panics in weird ways.

**Comment by pdeljanov** [comment]
You'll need at enable the `aac` to play AAC audio. The `isomp4` feature just enables support for the MPEG4/MOV/M4A/ISO container.

Do you have a stack trace when you disabled `isomp4`? It's likely your file got misdetected as something else and caused a panic when it tried to play. That shouldn't happen. Thanks!

**Comment by happysalada** [comment]
If I disable isomp4, the codec parameters I get for the track are
```
CodecParameters { codec: CodecType(4099), sample_rate: Some(48000), time_base: Some(TimeBase { numer: 1, denom: 48000 }), n_frames: None, start_ts: 0, sample_format: None, bits_per_sample: None, bits_per_coded_sample: None, channels: Some(FRONT_LEFT), channel_layout: None, delay: None, padding: None, max_frames_per_packet: None, packet_data_integrity: false, verification_check: None, extra_data: None }
```
(it's missing the n_frames parameter. If I try to decode it anyway, it starts decoding, giving me a bunch of 0 as the sample then gives me a channel index out of bound).
(I'm using exactly (almost) the code you give as a quick starter. let me know if you need anything else).

If I enable the aac feature, I get a `unsupported codec: DecodeError("aac: invalid data")`
[song.tar.gz](https://github.com/pdeljanov/Symphonia/files/8238646/song.tar.gz)

I've include a gzipped file in case you are interested.

**Comment by pdeljanov** [comment]
Hi @happysalada,

Thanks for providing the file. The file is AAC audio contained in a MP4/M4A container (as opposed to a raw AAC stream).

This is what's happening in each case:

| Feature(s) Enabled | Behaviour |
|------------------|------------|
| `aac`, `isomp4` | The file plays properly. |
| `isomp4` | The correct format reader is auto detected, but the AAC decoder feature is disabled so it fails to play. This is the expected behaviour. |
| `aac` | Since `isomp4` is disabled, the format auto detector is missing the information that allows it to figure out that the file is a M4A file. So it keeps trying to search for something that looks familiar and it lands on a raw AAC stream. However the decoder fails to decode because it's missing data that is provided by the M4A container. |
| None | Same as above except since the auto detector doesn't know about AAC now either so it finds something that looks like MP3 data and tries that. This one panics due to a bug in the MP3 decoder. I've fixed that panic. |

There should be no more panics now, but there may still be misdetections depending on the features you enable. Unfortunately I need to make a breaking API change to improve the auto detector, so that part is on hold until I can find time to work on a v0.6. My recommendation in the mean time is to enable `isomp4` support.

**Comment by happysalada** [comment]
And it works! Thanks a lot!
Would you be open to accepting github sponsorships by any chance ? I would be happy to contribute. It might not be a lot per single person, but depending on how many people join, it could add up.

**Comment by pdeljanov** [comment]
Glad it's fixed now, and thanks for the sponsorship offer!

I've considered enabling sponsorships, but I'm not sure how I feel about accepting money if I can't always maintain a consistent project momentum. I've been very busy with my full-time employment lately so it's gonna be a slow few months for Symphonia. 😅

**Comment by happysalada** [comment]
I completely understand! :-)
Thank you again for the library!
