### ISSUE TITLE
Add `SampleBuffer::clear()`?

### ISSUE THREAD

**Issue by torokati44** [pdeljanov/Symphonia#126]
I found myself in a situation where clearing an existing `SampleBuffer` would be really useful.
If I understand it right, that would be only a matter of setting `n_written`  to `0`.

However, I found no way of doing this other than assigning a newly created, empty buffer to it.

Is this something that could be added perhaps?

**Comment by torokati44** [comment]
And somewhat related: What's the point of storing `n_written` next to a `Vec`?
AFAIK `Vec` has this functionality built in.
That is: it has a separate `capacity` and `len`.

**Comment by pdeljanov** [comment]
Hi @torokati44,

Having a clear method is a good idea. I haven't spent much time considering use cases for `SampleBuffer` outside of just grabbing samples from `AudioBuffer`s.

I've chosen not to resize the vector because it would likely involve extra zeroing operations, and/or extra allocations/deallocations. By managing the buffer myself I can avoid those.

That being said, it should really be a boxed slice of `S` instead of `Vec<S>` if the vector methods aren't being used.

**Comment by torokati44** [comment]
> Having a clear method is a good idea. 

Thanks for adding this to a milestone!

> I haven't spent much time considering use cases for SampleBuffer outside of just grabbing samples from AudioBuffers.

This is how it came up:
https://github.com/torokati44/ruffle/commit/c2ccacd4900a5e258d6cc1380a918110f946f9a7
I hope the surrounding code can provide more context as to why.

 > I've chosen not to resize the vector because it would likely involve extra zeroing operations
 
Okay, I see, that makes sense. I only considered the allocation part, which would likely(?) not take place, but the zeroing almost certainly would, yeah.

**Comment by torokati44** [comment]
Fixed by 10e8a2db2bb13a5d771ebb40db636e56a7c72cca.
Thanks a lot!
