### ISSUE TITLE
Format probe incorrectly detects mp3 file as aac

### ISSUE THREAD

**Issue by aschey** [pdeljanov/Symphonia#130]
When attempting to play [this file](https://mega.nz/file/IqgmjTwS#DMfxlYECsnmAjX9t_roTGMDLWij5BrH_cr4r-6w8-po) with `symphonia-play`, the following error is returned: ` ERROR symphonia_play > file not supported. reason? unsupported feature: adts: only 1 aac frame per adts packet is supported`. This is because the probe detects an aac marker [when it gets to the code here](https://github.com/pdeljanov/Symphonia/blob/41862b26699d6474c4e5d8415c50f1eab0972fe1/symphonia-core/src/probe.rs#L269), but the file is actually an mp3. When I disable the aac feature flag, the file plays fine. 

Seems like the easiest way to get around this would be to [pass along the hint](https://github.com/pdeljanov/Symphonia/blob/41862b26699d6474c4e5d8415c50f1eab0972fe1/symphonia-core/src/probe.rs#L305) to the `next` function and ensure that it checks the codec that corresponds to the hint before checking the other codecs, which should prevent false positives in the common case where the filetype is known. I guess a more robust way would be to make the markers stricter if possible or attempt to decode the first bit of the file before assuming the marker is correct, but that sounds messy. Curious what your thoughts are, thanks!

**Comment by pdeljanov** [comment]
Hi @aschey,

Yes, using the hint to prioritize certain readers would be a good and quick solution for the time being, though it wouldn't be robust in cases such when audio is being piped in.

A robust solution I had in mind is similar to your idea.

All `FormatReader`s that can be probed implement the `QueryDescriptor` trait. On this trait there is a `score` method that takes in a slice of bytes and is supposed to return a score of how confident it is able to play it. If multiple readers match on the same marker then the one with the highest score would be selected.

The only issue is that this trait was defined a very long time ago and I think it needs to be modified to allow it to ask for more data since the length of the byte slice would change dramatically depending on the format and the encoding parameters.

**Comment by aschey** [comment]
Thanks for the reply; that makes a lot of sense. I don't think I have the knowledge necessary to implement the scoring method, but would you be interested in a PR for the quick solution as a temporary fix?

**Comment by pdeljanov** [comment]
Hi @aschey,

Sure, I'll gladly accept a PR.

Since the scoring process will add overhead to format detection, being able to prioritize readers based on the hint will be  very desirable to mitigate some of that overhead. So this PR will be a good optimization in the long-run!

Just a heads up though, here are a few pitfalls and things to consider:

1. The list of registered format descriptors could be large in the future, so please try to avoid copying or reordering the descriptor list itself.
2. It's feasible for multiple readers to support the same format, so the hint could match with multiple registered format descriptors.
3. For media sources that are not a file, it's likely the mime-type will be used instead of an extension. Please consider both extension and mime-type (logic should be the same for both) when selecting which formats should be prioritized.
4. The extension string and/or mime-type provided in the hint should likely be normalized to lowercase.

**Comment by aschey** [comment]
Thanks for the tips; that's very helpful! I'll try to get around to this soon.

**Comment by pdeljanov** [comment]
This should now be fixed in the `dev-0.6` branch.
