### ISSUE TITLE
Division by zero when loading .wav file

### ISSUE THREAD

**Issue by StygianLightning** [pdeljanov/Symphonia#155]
When trying to load a test sound with [kira](https://docs.rs/kira/latest/kira/), I ran into an error ('attempt to divide by zero') originating at https://github.com/pdeljanov/Symphonia/blob/v0.5.1/symphonia-core/src/audio.rs#L295.

I verified that the same error occurs when running the getting-started example from symphonia directly.

The test sound can be found at https://github.com/StygianLightning/lyre/blob/main/examples/resources/birds.wav.

The problem may very well be in the file; importing and exporting the file through Audacity fixes the problem.

**Comment by pdeljanov** [comment]
Thanks for reporting this @StygianLightning!

The file is not encoded correctly, but Symphonia should never panic when given bad input. The panic is fixed, though I'm leaving it unplayable for now since according to the Microsoft docs it's undefined what should actually happen if a file is encoded this way.
