### ISSUE TITLE
Mp3 performance on ARMv7

### ISSUE THREAD

**Issue by karlri** [pdeljanov/Symphonia#156]
I ran some benchmarks on symphonia on ARMv7 and all codec implementations are competitive against ffmpeg, usually beating it by a small margin. Awesome!

Against gstreamer:
In vorbis, symphonia beats gstreamer by almost a factor of 2 which is amazing.

For mp3 however, it seems that gstreamer (using mpg123) beats both symphonia and ffmpeg by almost a factor of 2. The same is not observed on x86_64 where performance is almost identical between all 3. Any ideas why this might be?

Feel free to close, I just thought I'd report my findings because it might be of interest to somebody. Keep up the great work! :)

**Comment by torokati44** [comment]
My very quick two-cent guess: autovectorization (to SIMD: SSE or NEON).
AFAIK Rust doesn't do it on ARM yet.
I'd be very happy to be proven wrong though.

**Comment by pdeljanov** [comment]
Hi @karlri,

That's really great to hear and even better than I expected!

Thinking out loud here, but ffmpeg implements its DSP and performance sensitive routines in hand-tuned assembly for most major architectures. Assuming your version of ffmpeg is built with those optimization enabled, then the Rust compiler must be emitting SIMD instructions for Symphonia to be competitive.

For the most part, the bulk of MP3 decoding is spent doing two things:
1. Decompressing the Huffman encoded data
2. Synthesizing the audio samples

The optimal solution for point 1 is a lookup-table based approach which I believe all three libraries implement. There's little room for creativity here, but the tuning could be different and may alter the outcome some.

For point 2, most libraries (Symphonia and ffmpeg included) use a complex FFT followed by additional post-processing to synthesize the final audio samples. However, there are more optimized algorithms that exist in the literature for MP3 specifically. Generally, the FFT is preferred because it can be applied to many other decoders and the performance gain for more specialized algorithms is marginal. My guess is that mpg123 is using a more specialized algorithm, and perhaps the algorithm is more cache and/or memory bandwidth friendly. Thus leading to bigger gains on more constrained ARM systems.

Finally, mpg123 is an extremely optimized library. Symphonia passes on a few potential optimizations for the sake of code clarity. However, these optimizations may make a difference depending on the type of audio being decoded. I recommend testing a variety of genres.

If you are really interested in digging deeper, a `perf` trace of Symphonia could identify the decode step(s) that are responsible for the slowdown.

**Comment by Shnatsel** [comment]
@karlri please try building with `RUSTFLAGS='-Ctarget-cpu=native' cargo build --release` and then re-running the benchmarks.

ARMv7 does not provide any SIMD instructions by default, but many ARMv7 CPUs support SIMD (NEON). By default all compilers create an executable that runs on all ARMv7 CPUs, and that means not using any SIMD; the `-C target-cpu=native` flag will override it and build an executable for your CPU specifically, which will use SIMD via auto-vectorization.

It's possible that mpg123 does dynamic CPU feature detection and uses SIMD even without explicitly being compiled for newer CPUs; that would explain the large gap in performance.

**Comment by pdeljanov** [comment]
There's been some performance improvements to the MP3 decoder over the past week or so. I wonder if they help here?

**Comment by karlri** [comment]
Indeed the mp3 performance has improved! It has almost reached parity with mpg123. Now I can make the switch! However, I need to explicitly disable neon and other vector instructions. If I enable them, performance gets worse on my armv7 hardware, at least on some optimization levels. I find that opt-level=2 and -Z target-feature=-neon produces the best binary in my case. Keep up the great work!
