### ISSUE TITLE
Basic examples

### ISSUE THREAD

**Issue by ndarilek** [pdeljanov/Symphonia#17]
Hello,

Found your library while surveying the landscape of Rust audio decoders. I'm trying to decode arbitrary audio codec data into raw bytes for use in Alto.

Unfortunately, I've spent about half an hour looking through the code and can't seem to figure out what my entrypoint should be. Mind pointing me to where I'd look to, say, ingest arbitrary bytes and decode them? Or, if I need to know the incoming content type first, where I'd go to do that? I'm working with a game engine that hands me raw bytes, though it also gives me a path from which I can perform reasonable content-type detection. I'm

Thanks!

**Comment by ndarilek** [comment]
OK, looks like symphonia-play is what I need. Maybe a note in the README.md to that effect would help? The crate names aren't hugely helpful on their own. :)

I'll put together a PR for that soon if no one gets to it first.

**Comment by pdeljanov** [comment]
Hey @ndarilek,

Glad you managed to figure it out. :smile: 

You're right, the README documentation is lacking. Definitely need to update the main README and probably all the others before the next version is published!

**Comment by daniellga** [comment]
Hi! First of all, thank you for this amazing crate. I am trying to represent an audio example (flac) as a vec but I am having the same problem as the guy who created this issue. While in claxon I managed to achieve this reasonably fast, I am struggling to discover what to do here. Do you have any hints of what I can do to achieve this?

**Comment by pdeljanov** [comment]
Hi @daniellga,

At the moment the current best example is `symphonia-play`. Unfortunately it has become a bit complex since it has to handle all the use-cases Symphonia supports.

Here's a [gist](https://gist.github.com/pdeljanov/3cc26a350c5fb0462c2fa65ffff27079) of the most basic decode loop one could implement. Note that there is no error handling!

I'll be adding this as an example in a bit. Based on the feedback in this ticket it sounds like more examples should be provided, but also probably a simpler interface that exposes a sample iterator.
