### ISSUE TITLE
Refresh benchmarks

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#174]
BENCHMARKS.md lists results from 2019. The upcoming release 0.5.2 incorporates many performance improvements, and Symphonia now beats FFmpeg when decoding most formats. The benchmarks should be updated prior to the release.

**Comment by pdeljanov** [comment]
It would be nice, especially since lots of gains were made recently, but I'm short on bandwidth.

We do have the `benchtest.py` script, but it's outdated at this point and not at all comprehensive.

Ideally, `benchtest.py` would be updated to include more test vectors for all supported decoders, and to output markdown that can be pasted into `BENCHMARKS.md` directly. Otherwise, it's a real chore to update benchmarks. :(

**Comment by Shnatsel** [comment]
https://github.com/sharkdp/hyperfine can output a markdown table with the results.

**Comment by pdeljanov** [comment]
Yeah, that's how I got the current set of benchmarks. However, they're just one file per benchmark.

To get a better and more meaningful number we need to run 15-20 (the more the better) files per decoder and take the average of the relative performance figure over all runs. Unfortunately, `hyperfine` is not able to do this for us.

The `benchtest.py` script is a good starting point though because if it's extended then we can have a reproducible benchmark and collect the results for different processors. As we've seen, the results on my Core i7 4790k are hugely different compared to your more modern AMD CPU, or even my M1 Pro MBP.
