### ISSUE TITLE
Not getting length of files and other decode errors

### ISSUE THREAD

**Issue by BillyDM** [pdeljanov/Symphonia#18]
I'm trying to create a realtime-safe disk-streaming algorithm for audio for our DAW project. https://github.com/RustyDAW/rt-audio-disk-stream

I figured Symphonia would be perfect for this. However, I can't seem to get it to work. I've created various test files in Audacity, and it's returning `None` as the number of frames in the file for some codecs like `wav` and `mp3`, and other codecs like `ogg` fail to decode.

I've created a test program with my decoder struct that I plan to use.
[symphonia_test.zip](https://github.com/pdeljanov/Symphonia/files/5895538/symphonia_test.zip)

This program outputs this for me:
```
[src/main.rs:25] file = "./test_files/wav_u8_mono.wav"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/wav_i16_mono.wav"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/wav_i24_mono.wav"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/wav_i32_mono.wav"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/wav_f32_mono.wav"
[src/decoder.rs:115] e = "pcm: unknown bits per (coded) sample."
[src/main.rs:34] e = Format(
    IoError(
        Custom {
            kind: UnexpectedEof,
            error: "end of stream",
        },
    ),
)
[src/main.rs:25] file = "./test_files/wav_i24_stereo.wav"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/ogg_mono.ogg"
[src/main.rs:34] e = Format(
    IoError(
        Custom {
            kind: UnexpectedEof,
            error: "end of stream",
        },
    ),
)
[src/main.rs:25] file = "./test_files/ogg_stereo.ogg"
[src/main.rs:34] e = Format(
    IoError(
        Custom {
            kind: UnexpectedEof,
            error: "end of stream",
        },
    ),
)
[src/main.rs:25] file = "./test_files/mp3_constant_mono.mp3"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/mp3_constant_stereo.mp3"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/mp3_variable_mono.mp3"
[src/main.rs:34] e = NoNumFrames
[src/main.rs:25] file = "./test_files/mp3_variable_stereo.mp3"
[src/main.rs:34] e = NoNumFrames
```

**Comment by pdeljanov** [comment]
Thanks for your interest in Symphonia.

I pushed 3 changes to address some of the random errors you saw, and to provide the number of frames for WAVE files.

Please note however that while there is support for OGG (the container format), we don't have a Vorbis decoder yet.

In regards to obtaining the number of frames:

In general, most of the fields in `CodecParameters` are optional because they may not be readily available to the demuxer. When a `Decoder` is instantiated with a set of parameters, it *may* supplement these parameters, and that updated set of parameters are then available on the `Decoder` object. Though, the parameter you're interested in may not be available.

Unfortunately, the number of frames cannot always be determined. MP3 is *especially* bad for this. It's only possible to guess based on the average bitrate and file size, which wouldn't necessarily be accurate. It's simply not possible to determine the number of frames for MP3 and some AAC files without scanning the entire file, and that's something Symphonia doesn't do.

A generalized solution would be to simply decode the file and count the number of samples if the parameter is unavailable. That will get you an accurate sample count.

**Comment by BillyDM** [comment]
Wow, that was fast. Thanks!

Oh, I didn't realize that `ogg` was just a container format. That makes sense now.

The point of this realtime disk streaming algorithm is so you don't need to load the entire file into memory when you load it into a project, especially when the file is very long (like hours of podcast recordings). The DAW needs to know the number of samples to accurately know the start and end positions, and the algorithm needs to now the length to automatically wrap-around to the beginning when it hits the end of the file. I suppose we could make an exception for `mp3` files and such, as there probably isn't too many hour-long `mp3` files out there.

The `wav` format is the most important to us though, so thanks for fixing that!

**Comment by BillyDM** [comment]
A quick question, do you plan on supporting encoding with this library as well? It's not that important at the moment, but it would be cool if that was in the roadmap.

We only really need `wav` encoding for our DAW project. That should be simple enough to write our own encoder for it, but it would be nice if we could use this library for that as well.

**Comment by BillyDM** [comment]
Oh yeah, as for `mp3`, is it even possible to seek to a time position without decoding the entire file up-front?

**Comment by BillyDM** [comment]
Aha! It seems like there is an out-of-spec header for mp3 files added by encoders like `lame` and `ffmpeg` that encode length. https://github.com/lieff/minimp3#track-length-detect

**Comment by pdeljanov** [comment]
> The point of this realtime disk streaming algorithm is so you don't need to load the entire file into memory when you load it into a project, especially when the file is very long (like hours of podcast recordings). The DAW needs to know the number of samples to accurately know the start and end positions, and the algorithm needs to now the length to automatically wrap-around to the beginning when it hits the end of the file. I suppose we could make an exception for `mp3` files and such, as there probably isn't too many hour-long `mp3` files out there.

I think I understand your use case better now.

So a MP3 file is just a series of semi-independent audio packets of length 576 or 1152 audio frames long. The file contains no headers, indexing, or position information. Therefore, there is no total packet count, and given a random audio packet, it's not possible to know where it is in the stream.

For constant bitrate MP3s, theoretically these packets should be the same size, but not always due to padding. If the packets were constant size, then we could just divide the length of the file by the packet size, but unfortunately that'll be wrong in some cases.

And for VBR, well, then we can get a rough estimate of the number of frames by figuring out the average bitrate, but that's also going to be off in a lot of cases.

> Oh yeah, as for `mp3`, is it even possible to seek to a time position without decoding the entire file up-front? Even if we decode the entire file up-front to get the number of frames, can we still unload it to save memory and then seek to a position to load only a portion of it?

Seeking is another troublesome aspect. Since there's no index or positioning information it's hard to know where to jump. Many players will simply guess based on the average packet size, but that's inaccurate. Another annoying seek issue is that MP3 audio packets often refer to data in previous packets. So actually, it's not even possible (without audio glitches) to just start decoding at the packet containing the sample you're interested in!

MP3 is such a problem child...

To answer your question though, you do not need to decode to seek. You just need to call `seek()` on the `FormatReader` (i.e., `Mp3Reader`) object. All `FormatReader`s provide a sample-accurate `seek()` function (seek's to the packet containing the sample). After the seek, re-instantiate the decoder and feed it packets.

For the MP3 reader, `seek()` is implemented by sequentially parsing packets until it finds the proper packet for the sample requested. If you are seeking forward from the last packet, we can start scanning from the current position vs. the beginning of the file. The main bottleneck here is IO speed, not CPU performance, because we don't have to decode the actual audio.

Future iterations of Symphonia will incrementally build a seek index as the file is played, and also introduce the option to do an inaccurate seek. There's lots of "hacks" we can do to improve the situation, but they all have trade offs.

Also, while you should decode the packets to count frames (for now), the `Packet` object returned by `next_packet()` does have a timestamp and duration field that can be used to count frames. Those fields just aren't properly populated on some `FormatReader`s yet so I didn't want to recommend it.

> Aha! It seems like there is an out-of-spec header for mp3 files added by encoders like `lame` and `ffmpeg` that encode length. https://github.com/lieff/minimp3#track-length-detect

In regards to that out-of-spec header. I've never encountered it on any files in my library, so it's probably too rare to really rely on.

> A quick question, do you plan on supporting encoding with this library as well? It's not that important at the moment, but it would be cool if that was in the roadmap.

In regards to encoding, I don't think that's something I'd be looking to implement. Not until all the decoders are finished and compliant. Of course, if anyone wanted to contribute encoders, I'd be happy to accept some PRs.

Hope that helps. Feel free to raise more issues as you find them. There's likely some rough edges you'll run into!

**Comment by BillyDM** [comment]
Okay, thanks for your help!

Mp3 definitely does put a big wrench in things. I think I'll just focus on getting `wav` working for now and worry about other codecs when the time comes.

Cool project by the way! It means one less C dependency for us. :)
