### ISSUE TITLE
How to use with a stream of bytes?

### ISSUE THREAD

**Issue by sanfilippopablo** [pdeljanov/Symphonia#181]
Hi! 

I want to use symphonia to decode an mp3 stream coming from HTTP, which I get using reqwest, which gives me a stream of bytes. Any pointers of how to make that work with symphonia?

**Comment by erikas-taroza** [comment]
Hello.

I have implemented streaming mp3 over HTTP. [Here is the code](https://github.com/erikas-taroza/simple_audio/blob/e4f3312a79778b83a438d62806e4be7dbc4ac8b6/rust/src/audio/streamable_file.rs) if you want to take a look at how I did it.

**Comment by sanfilippopablo** [comment]
That's exactly what I was looking for. Thank you!

**Comment by erikas-taroza** [comment]
No problem :)

**Comment by sanfilippopablo** [comment]
Actually, not quite. I see this depends on being a full file and knowing the length in advance (it needs to read content-length), while I need to read an "infinite" mp3 stream, no content-length available. But this is a good starting point anyways.

**Comment by erikas-taroza** [comment]
You can modify `read` and return `false` in `is_seekable()`. I am not sure how Symphonia will handle decoding this, so best of luck.

Maybe @pdeljanov has more information.

**Comment by pdeljanov** [comment]
@erikas-taroza is correct. Your `MediaSource` still needs the `Seek` trait to be implemented, but you can leave the functions `unimplemented!()` or have them `panic!()`. If `is_seekable()` returns `false`, Symphonia will not seek the source. You will still be able to call `seek` on a `FormatReader` and it would likely succeed if the timestamp is in the future since we can emulate it by consuming bytes. Otherwise it'll return an `Error::SeekError`.

You can also just instantiate a `symphonia::core::io::ReadOnlySource` with any object that implements `Read` to take care of that for you. This is how `symphonia-play` wraps and uses `std::io::stdin` as a source.

You can play around with this using `symphonia-play` and trying any of the following:

```
cat /path/to/file | symphonia-play -
curl -s https://radio.station.com/stream | symphonia-play -
youtube-dl -f 140 <url> -o - | symphonia-play -
yt-dlp -f 140 <url> -o - | symphonia-play -
```
