### ISSUE TITLE
Metadata Tags Write

### ISSUE THREAD

**Issue by FadyQJ** [pdeljanov/Symphonia#239]
I would just like to know if you have any plans to support writing metadata or it is not part of the roadmap?

I can make a PR with it sometime in the future once I reach the point in my project where I need this feature if that is possible

**Comment by pdeljanov** [comment]
Hi @FadyQJ,

I don't have any plans for write support be it metadata, muxing, or encoding. I'm not opposed to it in principle, but I'm not sure how it would fit into Symphonia. It would also be quite a bit of work to develop and maintain, so I could only accept it if one or more people commit to developing and maintaining it. Otherwise, I don't have the bandwidth to do it.
