### ISSUE TITLE
MediaSourceStream is not Send

### ISSUE THREAD

**Issue by james7132** [pdeljanov/Symphonia#24]
Due to wrapping a `Box<dyn MediaSource>` instead of `Box<dyn MediaSource + Send>`, MediaSourceStream is not safe to send across thread boundaries. Is this intentional?

**Comment by pdeljanov** [comment]
Not really intentional.

Symphonia was initially just a project for me to learn Rust, so multi-threading was not something I was thinking about. The original design was actually pretty hostile to multi-threading, but it is better suited to it now.

I believe it would be advantageous if `MediaSourceStream`, `FormatReader`s, and `Decoder`s can all be moved between threads, though I haven't considered all the implications.
