### ISSUE TITLE
[Feature request] Proivde a way to transfer whole buffer from the SampleBuf

### ISSUE THREAD

**Issue by dmtrKovalenko** [pdeljanov/Symphonia#264]
I need to get my audio as a plain Vec<f32> and everything is very good with symphonia, except that I can't get the data out of your `SampleBuffer` struct. 

```rust
let buffer: Box<[f32]> = sample_buf.into_owned_buffer()
// or 
let buffer: Vec<f32> = sample_buf.into_vec()
```

without copying the buffer by transferring the ownership outside of SampleBuffer

**Comment by pdeljanov** [comment]
Since Symphonia's `AudioBuffer` stores audio in a planar format (1 buffer per audio channel), `SampleBuffer` was added as a utility to easily interleave samples into another buffer.  In v0.5.x, there is no way to take the underlying buffer backing the `SampleBuffer` directly. The intention was to not create additional allocations. So you must copy the samples from it.

In v0.6, I am removing `SampleBuffer` and will have methods directly on `AudioBuffer` that will allow your to copy the samples into slices, vectors, etc., in planar or interleaved format.

For now, you can avoid this additional copy by accessing the samples in the `AudioBuffer` directly via the `planes` function. This function returns you a slice of samples for a particular audio channel. You can then interleave the samples yourself into your own buffer.

Hope this helps.

**Comment by pdeljanov** [comment]
This should now be easy to do with the `dev-0.6` branch in f1722b6de5fc2cc4a2fd2d56aeda211dcdf8f164`. Might be a while yet before 0.6 is released though.
