### ISSUE TITLE
README claims support of AAC profiles other than AAC-LC using non-existent feature flags

### ISSUE THREAD

**Issue by hikari-no-yume** [pdeljanov/Symphonia#266]
At the time of writing, the README claims Symphonia supports not just AAC-LC, but also HE-AAC and HE-AACv2:

https://github.com/pdeljanov/Symphonia/blob/7938624b77f39319e5fd591ce55fcc3bc763d63b/README.md#L111-L115

This was a bit worrying to me because those are probably patent-encumbered. But luckily, the README claims there are separate feature flags for them, so I can easily avoid them.

Except… as far as I can tell, these feature flags don't exist, and never have? The AAC decoder only supports AAC-LC, right? Or am I wrong?

I looked at the “blame” output and found they were added to the README in this commit, which doesn't explain the change: https://github.com/pdeljanov/Symphonia/commit/0d333e96510ed1fdcf86a80c524dd8eecd730107.

Was that a mistake? The state before that commit would not be reassuring either, though, as it implies the AAC decoder supports more than just AAC-LC even when using just the `"aac"` feature.

**Comment by pdeljanov** [comment]
Hi @hikari-no-yume,

Symphonia only supports AAC-LC and has never implemented any part of HE-AAC(v2).

The README in the repository root (the one rendered on GitHub), is a project roadmap so it lists some decoders and formats that have not been implemented yet (status of "-") with the hope that maybe someone would like to contribute. The README in the `symphonia` meta-crate (the one rendered on crates.io) and the support tables in the documentation list only the implemented decoders and formats.

Our policy is to not enable any patent encumbered format or decoder by default. In fact, we only enable FOSS ones by default. Since AAC-LC is patent unencumbered but HE-AAC is not, I split the `aac` feature flag into `aac` and `he-aac`(`-v2`) feature flags to provide more flexibility.

If/when support is implemented, it would be implemented by the `symphonia-codec-aac` crate. However, that support would still be gated behind the `he-aac`(`-v2`) feature flags on that crate and the meta-crate, and they would be off by default.

I hope this clarifies the situation.

**Comment by hikari-no-yume** [comment]
Oh I see, I should have noticed the “Status” was “-”. Thanks for the clarification!
