### ISSUE TITLE
Artifact when decoding MP3

### ISSUE THREAD

**Issue by Herschel** [pdeljanov/Symphonia#28]
symphonia-bundle-mp3 decodes the following MP3 incorrectly:

[dash-fx.zip](https://github.com/pdeljanov/Symphonia/files/6566968/dash-fx.zip)
(32-bit float WAV of symphonia output included).

Expected waveform:
![image](https://user-images.githubusercontent.com/36278/120121374-f3b56900-c157-11eb-83d8-0bd831fe162c.png)

Symphonia output:
![image](https://user-images.githubusercontent.com/36278/120121368-e00a0280-c157-11eb-9b13-00e13cba7ba8.png)

**Comment by pdeljanov** [comment]
This appears to be an error in the Huffman decoding step. Haven't found the root cause yet. Oddly, this type of error is present on some malformed, yet playable, bitstreams. Not sure if this file is one of those streams. Even if it is, since it plays fine via. ffplay I'll be looking for a fix regardless.

**Comment by pdeljanov** [comment]
This one ended up being due to a typo! I'm kinda surprised it didn't result in more audible glitches for other files. Thanks for reporting!

**Comment by ousia** [comment]
To reference in the original report (ruffle-rs/ruffle#4273).

Many thanks for your fix, @pdeljanov.
