### ISSUE TITLE
Implementing `Decoder` for external codecs

### ISSUE THREAD

**Issue by FelixMcFelix** [pdeljanov/Symphonia#52]
I'm currently trying to implement the `Decoder` trait around libopus (via the audiopus crate) for a downstream project. We're trying to move from being dependent on ffmpeg, and currently support some uncommon Opus framing mechanism and PCM in our mixing/decoding setup.

However, there are some differences between Symphonia's buffer formats and those output by libopus. In particular:
* A stereo libopus decoder interleaves both audio planes, while `AudioBuffer` only allows stacked planes per frame. A consequence is that while I can get a large enough `&mut [f32]` to write into via `buf.chan_mut(0)` on a mono buffer, this interferes with correctly combining this with any other buffers. It can be wrangled into the correct planar format by simply creating a `Vec<f32>` and manually copying into the slices given by `buf.chan_pair_mut(0, 1)`, but this probably adds quite an overhead (especially if the target mixing `SampleBuffer` must be interleaved to be re-encoded by libopus).
* libopus can decode to stereo or mono independent of the number of channels in a `Track`, according to whatever the user needs (at the time the `OpusDecoder` is created).
* Missed packets can be passed in to Opus in general: I assume a `Packet` from a null slice would suffice here though.

(I haven't tried to implement [DCA](https://github.com/bwmarrin/dca) framing yet, but see no reason why it wouldn't work.)

Naturally, I could avoid registering a Symphonia codec entirely by just special-case handling any Opus tracks (which would also be used for e.g., direct packet passthrough), or taking the performance/memory hit to get data in and out of Symphonia's representation. But I'm wondering whether the following are future considerations for the design of the library:
* Support for interleaved channels in `AudioBuffer`. While this makes it easier to interface with external codecs (not a project goal to my understanding), it also should reduce overhead if the user knows that an interleaved output is needed. Is there any way to reconcile this with the `Signal` trait, given that this would prevent retrieving a plane as a contiguous slice? How much additional work would this be for the existing codecs?
* Passing in information about a target buffer--whether it is stereo/mono, f32/i16. Is `DecoderOptions` the right struct for this?

**Comment by pdeljanov** [comment]
Hey @FelixMcFelix,

Sounds like you're running into some of the rough edges of the API. Let's go over them and hopefully I can suggest some solutions.  Indeed, some of the issues you mentioned are on my to do list.


> Support for interleaved channels in `AudioBuffer`. While this makes it easier to interface with external codecs (not a project goal to my understanding), it also should reduce overhead if the user knows that an interleaved output is needed. Is there any way to reconcile this with the `Signal` trait, given that this would prevent retrieving a plane as a contiguous slice? How much additional work would this be for the existing codecs?

So this is a pretty big one to unpack. Symphonia is designed to be extendable by the user. All of Symphonia's decoders and demuxers are built solely using the public interfaces of the core library. So what you're trying to do by wrapping `libopus` is a valid use-case. While it's not a stated project goal, I do want to experiment with wrapping the libraries of more obscure audio formats, such as `libopenmpt` for tracker music, so that they may be used with Symphonia.

In regards to interleaved `AudioBuffer`s, the `Signal` trait exposes many functions that provide contiguous slices of samples. It's therefore completely incompatible with interleaved audio buffers. The thing is, while interleaved buffers are good for streaming audio, it's not very useful for implementing decoders. I imagine libopus internally also uses a buffer per channel and then interleaves it at the end. So because of that, Symphonia has never had a need for them. While the `Signal` trait could be rewritten to make it compatible with both planar and interleaved buffer formats, it'd come at the performance and memory penalty for our decoders.

A possible alternative is extending `AudioBufferRef` with new `InterleavedAudioBuffer` variants. Since the decode function actually returns an `AudioBufferRef`, this is an unobtrusive solution.

That being said, I think right now you should just take the performance hit and deinterleave the buffer you get from `libopus` and write it into an `AudioBuffer`. The cost really is going to be negligible. Here is a simple example of how that could be done (might need some tweaks to make it compile).

```rust
// Clear audio buffer (if reusing the same buffer).
output.clear();

// Reserve space in audio buffer (assuming input is a slice of samples from libopus).
output.render_reserved(input.len() / num_channels);

for ch in 0..num_channels {
    // Iterate over each ch-th sample in the input buffer.
    let iter = input.chunks_exact(num_channels).map(|chunk| chunk[ch]);
    // Alternative: let iter = input[ch..].iter().step_by(num_channels); 

    // Copy input sample to output sample in the AudioBuffer.
    for (o, i) in output.chan_mut(ch).iter_mut().zip(iter) { *o = i; }
}
```

> Passing in information about a target buffer -- whether it is stereo/mono, f32/i16. Is `DecoderOptions` the right struct for this?

Yup, that is expected use-case for `DecoderOptions`. Only issue is that right now the set of options has to be generic across all decoders, but I plan in the future to allow specifying custom options.

However, is there a reason why you need to specify `f32` or `i16`?

I mostly understand selectively decoding stereo or mono (does it down-mix stereo into mono, or just output a single channel?), but unless `libopus` implements both a fixed and floating point decoder then it's likely just internally converting one or the other to the user's preferred format. In Symphonia, when you copy an `AudioBuffer`/`AudioBufferRef` to another `AudioBuffer`, `SampleBuffer`, or `RawSampleBuffer`, it'll automatically convert the sample format for you, so decoders don't need to be responsible for this. 

However, if `libopus` actually does implement both a floating point and fixed point decoder, such that there's a tangible performance difference based on that option, then I'd recommend creating two different `Decoder`s: one for fixed point and one for floating point. Then, only register the one you want in your `CodecRegistry` based on whatever criteria you choose.

Eventually, Symphonia will have it's own Opus decoder, so some of this may become moot :).

**Comment by FelixMcFelix** [comment]
Thanks for the detailed response – I think that the costs tend to be dwarfed by later re-encoding anyway, so I suppose that's an acceptable cost to pay in the mean time. I don't know too much about the internals of the Opus codec, but this seems a reasonable choice. I suppose the new variants if needed in future would be `Interleaved(Cow<'a, (SampleBuffer<S>, Channels)>)` or similar.

> However, is there a reason why you need to specify `f32` or `i16`?

The output sample type was given more as an example (Opus does [decode to `i16`](https://github.com/xiph/opus/blob/master/src/opus_decoder.c#L775-L780) and then just converts from there). The stereo/mono difference is a bit more important, since the codec will average left and right channels when converting to mono, and duplicates single channels when mixing to stereo – but this can also be manually handled if need be.

That will be exciting to see! I think that we'd be better served by keeping the libopus variant though, since we need to use it for its encoder regardless. Closing for now, since I think this answers the design/roadmap questions I had. Thanks again.
