### ISSUE TITLE
ALAC support

### ISSUE THREAD

**Issue by inflation** [pdeljanov/Symphonia#60]
Hi, I’m really excited to see this project! I have some experiences on ALAC codec and am eager to help. What would be best for the collaboration?

**Comment by pdeljanov** [comment]
Hi @inflation,

Thanks for your interest!

Coincidentally enough, ALAC is something I've been working on. So far, I've made some progress on extending the `IsoMp4Reader` to support demuxing ALAC (among other) bitstreams and have not gotten to the decoder yet. If the decoder is something you'd like to write, then it's not too late to jump in.

There is no specification for the ALAC codec. We only have Apple's official [reference implementation](https://github.com/macosforge/alac) to work with. This means that for the most part, we just need to port the reference implementation over to Rust, and make it idiomatic (i.e., use iterators instead of for loops, etc.).

A good starting point would be to look at the [PCM decoder](https://github.com/pdeljanov/Symphonia/blob/master/symphonia-codec-pcm/src/lib.rs) to understand how a Symphonia decoder is structured (the `Decoder` trait). Then check out the [FLAC decoder](https://github.com/pdeljanov/Symphonia/blob/master/symphonia-bundle-flac/src/decoder.rs) to see how a similar lossless audio decoder is implemented.

If this is something you're interested in working on, you can jump right in.

Since this is something I was planning to include in v0.5 (next release), please keep me posted occasionally on your progress, and let me know if you won't be able to complete it for whatever reason.

Of course, please feel free to reach out and ask if you have any questions or are getting stuck.

**Comment by inflation** [comment]
Sure, I will read the source and start on porting the reference implementation.

**Comment by inflation** [comment]
I'll need more time on this because of personal issues. Feel free to take it over. Sorry.
