### ISSUE TITLE
Clarify how ffmpeg was referenced for symphonia-bundle-flac

### ISSUE THREAD

**Issue by tesselode** [pdeljanov/Symphonia#65]
symphonia-bundle-flac's readme acknowledges ffmpeg for "algorithm clarifications". ffmpeg is licensed under LGPL - could this be a problem for symphonia, which is MPL-2.0 licensed?

**Comment by pdeljanov** [comment]
Hi @tesselode,

The FLAC decoder was written from the specification. However, due to the specification not being complete and sometimes ambiguous, I needed to reference the FLAC reference library and ffmpeg for clarity on certain points. This means checking that the output of the ambiguously defined algorithm as implemented in Symphonia matched the other decoders.

The only exception to this is the `rice_signed_to_i32` function which implements a bit twiddling hack I first observed in ffmpeg, but is also found in other MIT licensed FLAC decoders such as Claxon.

I don't believe this should be a concern. However, if the last point concerns people enough to the point they won't use Symphonia, then I can think of a different implementation, albeit at the cost of performance.
