### ISSUE TITLE
aac file doesn't play in rodio with error «invalid data»

### ISSUE THREAD

**Issue by Rrogntudju** [pdeljanov/Symphonia#67]
I can play the file with ffplay or the windows default decoder. I played the file in symphonia-play : the error occurs at line 370 of aac.rs.

validate!(
    (self.window_sequence == ONLY_LONG_SEQUENCE)
        || (self.window_sequence == LONG_START_SEQUENCE)
);

I attached a sample of the first 1 second
[error.zip](https://github.com/pdeljanov/Symphonia/files/7574926/error.zip)

**Comment by pdeljanov** [comment]
The file plays okay with `symphonia-play`. The only issue I see is that it drops the first chunk of samples due to a decode error at the start of the file. The error is reasonable, though Symphonia could be more lenient about the underlying cause. I will work on fixing that.

However, if Rodio isn't playing it at all, then that likely means they're not ignoring decode errors. Decode errors are a non-fatal error so this would be something they have to fix since many legitimate files do indeed have sections of corrupted data that can't be decoded.

**Comment by Shnatsel** [comment]
Looks like this is fixed upstream: https://github.com/RustAudio/rodio/pull/403
