### ISSUE TITLE
Vorbis: Mismatch with max delta from 0.001 to 1.25

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#71]
[Data link](https://mega.nz/file/Yo9TRAZZ#bdInwjxbHSOqZ-PQvyg9dMOYfajq6mK4oFBAAo8hga8)

The high-delta mismatches are likely simply misaligned, although I haven't been able to confirm that.

I have excluded files with max delta below 0.001.

Tested on commit 16497ee5fb0d2f00287ba3444c52b22bc4debdae

**Comment by pdeljanov** [comment]
Thanks, I'll take a look.

Many Vorbis and AAC streams are going to have relatively large errors (but still < 0.001 and inaudible) because the current implementation of the IMDCT is not as numerically accurate as it should be. This isn't a problem with MP3 because it uses small IMDCT transforms so the errors are negligible. However, Vorbis and AAC may use larger transforms and then the error becomes apparent.

I'm working on switching to a IMDCT based off of a FFT with better numerical accuracy. So this will be resolved relatively soon. You may want to hold off on testing Vorbis and AAC until then. That being said, any errors larger than 0.001 are likely something else and may warrant investigation. Vorbis should have less dropped packets than MP3 so misalignment shouldn't occur as often.

**Comment by pdeljanov** [comment]
All but two of these files are failing due to the accuracy issues mentioned above. So a fix for those will come soon.

However, the following two files are failing due to an extremely large amount of checksum errors causing a lot of dropped packets.

```
Diane & David Arkenstone/David Arkenstone - 1995 - Quest of the Dream Warrior- Kyla's Journey/09 - Wings of the Shadow.ogg
Diane & David Arkenstone/D & D Arkenstone - 2001 - [Earth Trybe 1] Trance World/02 - Shirashikkur.ogg
```

I'm not sure yet if I'll attempt to add workarounds for these since dropping packets with incorrect checksums is safer (less chance of ear-piercing audible glitches) than attempting to be lenient.

**Comment by Shnatsel** [comment]
> dropping packets with incorrect checksums is safer (less chance of ear-piercing audible glitches) than attempting to be lenient.

Yeah, that makes sense.

**Comment by Shnatsel** [comment]
I've asked around for more personal music collections because they tend to be far more eclectic than datasets. So here's [another set](https://mega.nz/file/kgNjCKjD#_fHz29ftSpSvMeN6Piu6mraIenuZo0ARY_JcZaU1vpU) of files with Vorbis decoding mismatches.

I assume it would be more efficient to test these after the the IMDCT rewrite lands, instead of spending time investigating a potentially well-known issue.

**Comment by pdeljanov** [comment]
Probably should hold off on testing more since yeah, most issues are gonna be duplicates at this point and I already have quite a backlog to work through and fix already lol..

**Comment by pdeljanov** [comment]
Made a bit of an improvement regarding those two broken files in the last commit. However, the issues with the above files aren't fully resolved.

With further tweaking[^1] I managed to completely "fix" one of the broken files, and reduce the fail count on the second to 12, but I think the behaviour is unsafe as mentioned above. I'll leave a note below in-case this comes up again in the future.

[^1]: On a page discontinuity, if the page before the discontinuity started, but did not finish, a packet, do not reset the partial packet buffer of the logical stream. Likewise, if a continuation page is expected, but the current page is not a continuation page, do not reset the partial packet buffer of the logical stream.

**Comment by roderickvd** [comment]
That FFT sounds exciting! Something like this? https://www.dsprelated.com/showcode/196.php That C snippet uses `fftw3` for which there are Rust bindings, but perhaps even better the native Rust https://crates.io/crates/rustfft.

Sorry if I'm linking to stuff you have probably long looked at. But I'm an audio buff myself and the prospect of greater numerical precision is something that just appeals to me.

**Comment by pdeljanov** [comment]
Hey @roderickvd,

Yeah, that code would do what's needed.

The current (I)MDCT implementation is derived from a DCT that's implemented using a Fast Cosine Transform (FCT). The implementation is fast, but it's not very numerically precise when the size of the transform becomes large.

An alternative solution is to use a DCT derived from a DFT that's implemented using a FFT. This should be more numerically precise at larger transform sizes.

I actually used `rustdct` (which uses`rustfft` under-the-hood) for the AAC decoder, but I replaced it with Symphonia's built-in IMDCT a while ago. Our current IMDCT is actually faster than `rustdct` which is nice, but again, we have the numerical precision issue.

So my plan is to implement a split-radix FFT in Symphonia and then migrate the DCT to that.

Symphonia has very few dependencies, and the ones it does have are extremely tiny. I don't really want to pull in something like `rustdct` for this since we don't need much more than a simple power-of-2 FFT. It's also not terribly difficult to implement, but I just need a good block of time to do it.

**Comment by pdeljanov** [comment]
The accuracy issue should now be fixed with the latest commit.

Any failures with the Vorbis or AAC decoders are now likely to be due to dropped packets, corruption, or a bug in the decoder.

I'm going to leave this open because that second set of Vorbis files seem to still have legitimate issues decoding.

---

Before FFT:
```
Test Results
=================================================

  Failed/Total Packets:        10886/       23501
  Failed/Total Samples:     11874530/    34403326

  Absolute Maximum Sample Delta:       0.00055047

FAIL
```

After FFT:
```
Test Results
=================================================

  Failed/Total Packets:            0/       23501
  Failed/Total Samples:            0/    34403326

  Absolute Maximum Sample Delta:       0.00000036

PASS
```

**Comment by roderickvd** [comment]
That's totally awesome. Two questions glancing at the code:

1. Would turning this into `f64` bring anything, or perhaps the other way around, _cost_ anything? In `librespot` I toyed around with the performance impact of `f32` versus `f64`. I didn't use proper benchmarks but just by looking at CPU usage in `top` on various platforms there was no perceivable difference, so I went for `f64`. Because most platforms have native 64-bit support (even on a 32-bit kernel), that explains why CPU usage isn't impacted, but at the expense of four more bytes of RAM of course.

2. On the same page have you done any benchmarking on the inlining? I generally let the compiler try and do the smart thing, and only override when it was proven necessary: https://stackoverflow.com/a/37639889

**Comment by pdeljanov** [comment]
Hi @Shnatsel,

The last commit fixes all the files in the second set. I believe that covers all the issues raised in this ticket. As such, I will close the ticket. Do you have any other data sets to test against? If you do and find anymore issues, please open a new ticket.

---

Hi @roderickvd,

Those are some interesting questions. Let me give you my thoughts below.

> 1. Would turning this into `f64` bring anything, or perhaps the other way around, _cost_ anything? In `librespot` I toyed around with the performance impact of `f32` versus `f64`. I didn't use proper benchmarks but just by looking at CPU usage in `top` on various platforms there was no perceivable difference, so I went for `f64`. Because most platforms have native 64-bit support (even on a 32-bit kernel), that explains why CPU usage isn't impacted, but at the expense of four more bytes of RAM of course.

Using `f64` would most definitely improve the numerical accuracy, but it'd be marginal, and I don't know of any mainstream decoders that do! Also, every OS uses `f32` in their audio mixers.

I believe the reason why `f64` isn't used is because `f32` already provides 24-bits of dynamic range, which covers the human hearing range. Aside from that, there is definitely a performance cost, but it'd only be noticeable if you either have multiple concurrent decoders going, or if you measure how long it takes to decode a file in whole.

For example, Symphonia's Vorbis decoder is ~12% slower than `ffmpeg` on average. In terms of total decode time, this amounts to ~60ms for ~6 minutes of audio. Since the file is decoded in real-time and not all at once, this is an extra 0.160ms/s of audio playback. This amount just won't be visible on top.

The reason for `f64` being slower (on modern hardware) would be because it's double the amount of data, which means you can fit half as many samples per cache line, and per SIMD register. As you go back to older CPU generations, the `f64` performance will likely drop off just because it wasn't as optimized as `f32`.

For Symphonia, I use `f64` when I pre-calculate certain data tables, but I store the result as `f32`. I found that this does indeed improve the numerical accuracy. However, because I want Symphonia to work well on low-end systems like a RaspBerryPi, I don't think anything beyond that should be `f64`.

> 2. On the same page have you done any benchmarking on the inlining? I generally let the compiler try and do the smart thing, and only override when it was proven necessary: https://stackoverflow.com/a/37639889

I've found the compiler to do a good job, but not always. I also worry that maybe an inlining heuristic gets buggy in a 
 compiler release and Symphonia's performance tanks as a result. For this reason, I generally force inline on functions that I know will be called extremely frequently. This is mostly in the DSP or IO (bit reader) routines.

For the `fft` module specifically, I very much want the function calls to `fft16`, `fft8`, `fft4`, and `fft2` functions to be inlined because on a typical audio file they're called (in total) about 41 280 times per channel per second of audio! I use force inline to avoid having to unroll these functions myself.

For fun, I removed the force inline attribute on those fft functions, and the performance went from 12% slower than `ffmpeg` to 17%. The compiler did a very good job here, but a 5% difference is pretty massive in my opinion. I couldn't convince the compiler not to inline by using inline never. :laughing:

**Comment by Shnatsel** [comment]
Oh yes, I have downloaded 200Gb of random Vorbis torrents as soon as I saw you've rewritten the FFT. I'll leave a `symphonia-check` job overnight.

**Comment by roderickvd** [comment]
> The reason for `f64` being slower (on modern hardware) would be because it's double the amount of data, which means you can fit half as many samples per cache line, and per SIMD register. As you go back to older CPU generations, the `f64` performance will likely drop off just because it wasn't as optimized as `f32`.

Ah yes, the cache.
 
> For fun, I removed the force inline attribute on those fft functions, and the performance went from 12% slower than `ffmpeg` to 17%. The compiler did a very good job here, but a 5% difference is pretty massive in my opinion. I couldn't convince the compiler not to inline by using inline never. 😆

Certainly, that's absolutely significant. Out of interesting how about with just `#[inline]` where you hint the compiler to inline, but not force it?

**Comment by pdeljanov** [comment]
Tried to just use `#[inline]` and it inlined `fft32` (this one doesn't have an attribute on it), `fft8`, `fft4`, `fft2`, but it did not inline `fft16`. Very weird.

```
- symphonia_codec_vorbis::VorbisDecoder::decode_inner (inlined)
    + 41.27% symphonia_codec_vorbis::residue::Residue::read_residue
    - 34.85% symphonia_codec_vorbis::dsp::DspChannel::synth
        - 32.36% symphonia_core::dsp::mdct::Imdct::imdct
        - 17.23% symphonia_core::dsp::fft::Fft::transform
            - 14.61% symphonia_core::dsp::fft::Fft::transform
                - 11.73% symphonia_core::dsp::fft::Fft::transform
                    - 9.29% symphonia_core::dsp::fft::Fft::transform
                    - 6.65% symphonia_core::dsp::fft::Fft::transform
                        - 6.53% symphonia_core::dsp::fft::fft32 (inlined)
                            - 4.74% symphonia_core::dsp::fft::fft16
                                - 2.22% symphonia_core::dsp::fft::fft8 (inlined)
                                - 0.83% symphonia_core::dsp::fft::fft4 (inlined)
```

**Comment by Shnatsel** [comment]
Now that DCT is more accurate and all the mismatches from the files are provided are fixed, shouldn't Vorbis be bumped to "Excellent" in README.md?

**Comment by pdeljanov** [comment]
@Shnatsel, I usually edit the README before I tag the release. I will classify Vorbis as excellent. Do you think your test coverage was sufficient to mark ALAC as excellent as well?

**Comment by Shnatsel** [comment]
I don't think my testing of ALAC was thorough enough to classify it as excellent. I am not familiar with the Apple ecosystem and could easily have missed some important cases, even though the initial results are really encouraging.
