### ISSUE TITLE
MP3: Mismatch with max delta from 0.001 to 0.92

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#72]
[These files](https://mega.nz/file/0k8ljSQI#SH66aB7g77JHuPuZhhRJuTulApQ7YW6G3tDLtDrQihE) exhibit mismatches compared to ffmpeg ranging from 0.001 to 0.92.

Some of them are probably just misaligned, but hopefully there are some valuable samples in there.

Tested on commit 0b67a2ddc3b4600f51f5c94d7551a70fffb5ca56

**Comment by pdeljanov** [comment]
These were a mixed bag.

A couple files had malformed bitstreams that produced audible artifacts when decoded. I've adjusted the decoder to handle these bitstreams better and the artifacts are now fixed. However, the rest of the files still contain mismatches.

Of the remaining files, a couple are due to what I've tracked down and believe to be actual errors in `ffmpeg`.

Finally, there are a few more files where Symphonia has identical output to `mpg123` and `libmad`, but where `ffmpeg` decodes a few packets differently. I spent a lot of time this week on tracking down where this difference could come from but have largely turned up empty. My guess is that one of the optimizations `ffmpeg` uses is being triggered incorrectly and causing some subtle glitches. I can't say that's conclusively the case, but it doesn't seem worth it to continue investigating these any further since `ffmpeg` seems to be the odd one out.

**Comment by Shnatsel** [comment]
Thanks a lot for looking into these!

I'll use the new version to run the comparison on a larger corpus. On my system `mpg123` is provided by `mpg321` and it has its own 2.0 delta mismatches against Symphonia that don't show up on ffmpeg, so I suppose I'll stick to ffmpeg for now. I suggest simply ignoring ffmpeg if it's being the odd one out - otherwise we'd spend way too much time investigating inaudible ffmpeg glitches instead of doing high-yield work on Symphonia.
