### ISSUE TITLE
ALAC: error: malformed stream: isomp4: overread atom

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#73]
I am seeing `error: malformed stream: isomp4: overread atom` reported at the end of (seemingly successful) playback on 2 files out of 985 I've tested (totaling 33Gb).

I'm not sure if that's valid or not for these files, but I thought I'd report it just in case.

Tested on commit 0b67a2ddc3b4600f51f5c94d7551a70fffb5ca56

[Link to the problematic files](https://mega.nz/file/Ag0WBJ7K#Q8ZJTVaV50eknOxEkBfo7V37F9SzxuKYkO2fzugfuHU)

**Comment by pdeljanov** [comment]
This is a minor bug I've encountered on some MP4 files. Instead of an end-of-stream error it returns this error instead. Since it's an issue with the MP4 demuxer and only occurs at the end of a file, if you don't see any other failures then you can consider the files a pass.

My plan is to fix this for v0.5.

Thanks for testing so many ALAC files as well. I have very few so it's good to know the decoder is working well!

**Comment by Shnatsel** [comment]
I've thrown another 928 files at it for a total of 1913 and that is the only failure I've seen.

I also fed it ~180 Gb of FLAC, likewise with no errors.

**Comment by pdeljanov** [comment]
This should be resolved now. :)
