### ISSUE TITLE
MP3: Mismatch with max delta up to 2.0

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#99]
[These files](https://mega.nz/file/89UDma7L#WFh50099KpYXdWGFzTY2NghJGK8Iu1r6FGtkFs_jSww) show max delta up to 2.0 when compared against `ffmpeg` with `symphonia-check`.

I meant to test against `mpg123` as well, but on my system `--ref mpg123` always results in 0 samples compared, even though mpg123 itself seems to work. I suggest you run the check against mpg123 as well and only investigate files that diverge with both decoders, because this time it's a lot of files!

Tested on commit 898ee01ff9785eff54782da85124c32d9cdadfc9 (latest as of this writing).

The files are from the Pony Music Archive corpus and should be free to redistribute. I like this corpus because it contains files produced by a wide variety of encoders. I have previously run the test on a subset of this corpus; I've pruned the files I've already reported from the archive. I have run the check on the entire corpus this time; this amounts to roughly 200Gb of MP3 (27552 individual files).

**Comment by Shnatsel** [comment]
The vast majority of these files also diverge with libmad (invoked via `mpg321`).

**Comment by Shnatsel** [comment]
With `--no-gapless` only 32 files from the corpus diverge for more than 0.00001; so I assume most divergences have something to do with gapless playback.

They are already included in the archive linked above, but I've also uploaded them separately [here](https://mega.nz/file/d1lwgBCZ#IYaxFu-y3dmw8niSTIHcmI8t9Oy1lOZoargbRF5vW0M) for your convenience.

**Comment by Shnatsel** [comment]
Not directly related to this report, but: the FLAC portion of the corpus (~700Gb) passes with no divergences.

**Comment by pdeljanov** [comment]
This was a very good set in terms of surfacing some really weird encodings.

The vast majority of the files were just the Xing tag being encoded in a non-standard way causing Symphonia to ignore it and thus ignore the gapless data. I fixed many of these cases, however, I left one case emitting a warning instead. This case occurs when the Xing tag's CRC doesn't match. It seems like `ffmpeg` does not check the CRC, but this is weird to me. Maybe it works better IRL. I think we can revisit this later if it's a problem. So, while many of the files now pass (~67%), some still fail with a warning.

I also added other warning and info level messages to make triage simpler.

Of the 32 files that weren't fixed by using `--no-gapless`, only a couple were interesting.

There was one legitimate bug in the decoder that was triggered by these two files. It has been fixed now. This was a very good find and took a very rare combination of things to make it occur.
```
/Luna's Navel/fade 1.mp3
/Technote Wubs/Randomness/My Little Hangglider Music Remix.mp3
```

The following files were hitting the same `ffmpeg` look-up table bug that we saw in the last MP3 issue.
```
/Ace of 4's/6 Prong Star.mp3
/TempestShadow/Tempest Shadow - Tomb Raider.mp3
/TempestShadow/Pegapony - Tomb Raider [Trip Hop].mp3
```

For these files, `ffmpeg` doesn't recognize the Xing tag at all, while Symphonia does. This causes a misalignment when Symphonia trims the output samples.
```
/TGiuseppe94/What Your Friendship Means To Me (TGiuseppe94's Remix).mp3
/TheDashDub/Princess of the Night.mp3
/ZANDER/Robots Are Friendship.mp3
/ZANDER/Spiked.mp3
/ZANDER/Give Em' Hay (Pink Lady).mp3
/ponyphonic/Lullaby for a Princess (Original).mp3
```

These files have multiple Xing tags causing `ffmpeg` to play silence instead of discarding it. Symphonia will discard the packet and emit a warning without breaking the audio.
```
/Thomas Hood/The Magic Duel.mp3
/Crusader!/Updraft Feat. Vinyl scratch (Nowacking).mp3
/Ohmy/TeiThePony - Flying With The Rainbow (Ohmy Remix).mp3
```

These files work with `mpg123` but are broken with `ffmpeg`. I've seen this bug in `ffmpeg` before on other MP3 issues.
```
/Dave_Sherk/Atlantic world.mp3
/Dave_Sherk/Hope into heaven.mp3
```

The rest of the 32 files are corrupted or contained junk data.

A quick way to detect corruption is to run this command `ffmpeg -v debug -i path/to/file -f null -` and look for "header missing" logs. I've found that `ffmpeg` sometimes swallows a packet or two when this happens. Generally, Symphonia will just resync when this happens without dropping an extra packet. This difference will cause misalignment.

**Comment by pdeljanov** [comment]
Also, about `mpg123` not working... Due to #87, the `WavReader` needed to follow the WAVE standard more strictly to not break with certain files.

Unfortunately, when `mpg123` is streaming its output, it sets the audio data size to 0 instead of `0xffffffff` like all the other reference decoders. We'll likely need to introduce a `FormatOption` to allow non-standard behaviour.

If `mpg123` is provided by `mpg321`, then I think that'll work with no issues. Alternatively, changing [this](https://github.com/pdeljanov/Symphonia/blob/ee27dfdd2a60384627108132fcbe1742e2c181cb/symphonia-format-wav/src/lib.rs#L145) line to `let data_end_pos = u64::MAX;` is a quick workaround.

**Comment by Shnatsel** [comment]
I assume you've looked at all the files of interest, so I'm going to close the issue.

Thanks a lot for investigating, and so quickly too!

**Comment by Shnatsel** [comment]
And yes, I can confirm that the `mpg321` version of `mpg123` binary works fine. I understand in that case the file is decoded by libmad instead of the mpg123 decoder, but that's still a valuable point of reference.

**Comment by pdeljanov** [comment]
Hi @Shnatsel, thanks for confirming. Seems like `mpg123` is really the odd one out here.

I ran the entire 3.5GB archive through the decoder before pushing last night. All the broken files could be categorized into only a few major classes of issues. The majority being the Xing tag CRC failure. Everything that I thought was reasonable to accommodate, or was a plain bug, was fixed.

So, many files still "fail", but they've all been considered.
